<?php

use Illuminate\Database\Seeder;

class municipiosTabelaCidades extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('tb_cidades')->insert([
        ['nome'=>'Acailandia ','fk_uf'=>'10'],
        ['nome'=>'AfonsoCunha ','fk_uf'=>'10'],
        ['nome'=>'Agua Doce do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Alcantara ','fk_uf'=>'10'],
        ['nome'=>'Aldeias Altas ','fk_uf'=>'10'],
        ['nome'=>'Altamirado Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Alto Alegre do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Alto Alegre do Pindare ','fk_uf'=>'10'],
        ['nome'=>'Alto Parnaiba ','fk_uf'=>'10'],
        ['nome'=>'Amapa do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Amarante do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Anajatuba ','fk_uf'=>'10'],
        ['nome'=>'Anapurus ','fk_uf'=>'10'],
        ['nome'=>'Apicum-Acu ','fk_uf'=>'10'],
        ['nome'=>'Araguana ','fk_uf'=>'10'],
        ['nome'=>'Araioses ','fk_uf'=>'10'],
        ['nome'=>'Arame ','fk_uf'=>'10'],
        ['nome'=>'Arari ','fk_uf'=>'10'],
        ['nome'=>'Axixa ','fk_uf'=>'10'],
        ['nome'=>'Bacabal ','fk_uf'=>'10'],
        ['nome'=>'Bacabeira ','fk_uf'=>'10'],
        ['nome'=>'Bacuri ','fk_uf'=>'10'],
        ['nome'=>'Bacurituba ','fk_uf'=>'10'],
        ['nome'=>'Balsas ','fk_uf'=>'10'],
        ['nome'=>'Barao de Grajau ','fk_uf'=>'10'],
        ['nome'=>'Barra do Corda ','fk_uf'=>'10'],
        ['nome'=>'Barreirinhas ','fk_uf'=>'10'],
        ['nome'=>'Bela Vista do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Belagua ','fk_uf'=>'10'],
        ['nome'=>'Benedito Leite ','fk_uf'=>'10'],
        ['nome'=>'Bequimao ','fk_uf'=>'10'],
        ['nome'=>'Bernardodo Mearim ','fk_uf'=>'10'],
        ['nome'=>'Boa Vistado Gurupi ','fk_uf'=>'10'],
        ['nome'=>'Bom Jardim ','fk_uf'=>'10'],
        ['nome'=>'Bom Jesus das Selvas ','fk_uf'=>'10'],
        ['nome'=>'Bom Lugar ','fk_uf'=>'10'],
        ['nome'=>'Brejo de Areia ','fk_uf'=>'10'],
        ['nome'=>'Brejo ','fk_uf'=>'10'],
        ['nome'=>'Buriti Bravo ','fk_uf'=>'10'],
        ['nome'=>'Buriti ','fk_uf'=>'10'],
        ['nome'=>'Buriticupu ','fk_uf'=>'10'],
        ['nome'=>'Buritirama ','fk_uf'=>'10'],
        ['nome'=>'Cachoeira Grande ','fk_uf'=>'10'],
        ['nome'=>'Cajapio ','fk_uf'=>'10'],
        ['nome'=>'Cajari ','fk_uf'=>'10'],
        ['nome'=>'Campestre do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Candido Mendes ','fk_uf'=>'10'],
        ['nome'=>'Cantanhede ','fk_uf'=>'10'],
        ['nome'=>'Capinzal do Norte ','fk_uf'=>'10'],
        ['nome'=>'Carolina ','fk_uf'=>'10'],
        ['nome'=>'Carutapera ','fk_uf'=>'10'],
        ['nome'=>'Caxias ','fk_uf'=>'10'],
        ['nome'=>'Cedral ','fk_uf'=>'10'],
        ['nome'=>'Central do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Centro Novo do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Centro do Guilherme ','fk_uf'=>'10'],
        ['nome'=>'Chapadinha ','fk_uf'=>'10'],
        ['nome'=>'Cidelandia ','fk_uf'=>'10'],
        ['nome'=>'Codo ','fk_uf'=>'10'],
        ['nome'=>'CoelhoNeto ','fk_uf'=>'10'],
        ['nome'=>'Colinas ','fk_uf'=>'10'],
        ['nome'=>'Conceicaodo Lago-Acu ','fk_uf'=>'10'],
        ['nome'=>'Coroata ','fk_uf'=>'10'],
        ['nome'=>'Cururupu ','fk_uf'=>'10'],
        ['nome'=>'Davinopolis ','fk_uf'=>'10'],
        ['nome'=>'Dom Pedro ','fk_uf'=>'10'],
        ['nome'=>'Duque Bacelar ','fk_uf'=>'10'],
        ['nome'=>'Esperantinopolis ','fk_uf'=>'10'],
        ['nome'=>'Estreito ','fk_uf'=>'10'],
        ['nome'=>'Feira Nova do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Fernando Falcao ','fk_uf'=>'10'],
        ['nome'=>'Formosada Serra Negra ','fk_uf'=>'10'],
        ['nome'=>'Fortaleza dos Nogueiras ','fk_uf'=>'10'],
        ['nome'=>'Fortuna ','fk_uf'=>'10'],
        ['nome'=>'Godofredo Viana ','fk_uf'=>'10'],
        ['nome'=>'Goncalves Dias ','fk_uf'=>'10'],
        ['nome'=>'Governador Archer ','fk_uf'=>'10'],
        ['nome'=>'Governador Edison Lobao ','fk_uf'=>'10'],
        ['nome'=>'Governador Eugenio Barros ','fk_uf'=>'10'],
        ['nome'=>'Governador Luiz Rocha ','fk_uf'=>'10'],
        ['nome'=>'Governador Newton Bello ','fk_uf'=>'10'],
        ['nome'=>'Governador Nunes Freire ','fk_uf'=>'10'],
        ['nome'=>'Graca Aranha ','fk_uf'=>'10'],
        ['nome'=>'Grajau ','fk_uf'=>'10'],
        ['nome'=>'Guimaraes ','fk_uf'=>'10'],
        ['nome'=>'Humberto de Campos ','fk_uf'=>'10'],
        ['nome'=>'Icatu ','fk_uf'=>'10'],
        ['nome'=>'Igarape Grande ','fk_uf'=>'10'],
        ['nome'=>'Igarape do Meio ','fk_uf'=>'10'],
        ['nome'=>'Imperatriz ','fk_uf'=>'10'],
        ['nome'=>'Itaipava do Grajau ','fk_uf'=>'10'],
        ['nome'=>'Itapecuru Mirim ','fk_uf'=>'10'],
        ['nome'=>'Itingado Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Jatoba ','fk_uf'=>'10'],
        ['nome'=>'Jenipapo dos Vieiras ','fk_uf'=>'10'],
        ['nome'=>'Joao Lisboa ','fk_uf'=>'10'],
        ['nome'=>'Jose landia ','fk_uf'=>'10'],
        ['nome'=>'Junco do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Lago Verde ','fk_uf'=>'10'],
        ['nome'=>'Lago da Pedra ','fk_uf'=>'10'],
        ['nome'=>'Lago do Junco ','fk_uf'=>'10'],
        ['nome'=>'Lagoa Grande do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Lagoa do Mato ','fk_uf'=>'10'],
        ['nome'=>'Lagoa dos Rodrigues ','fk_uf'=>'10'],
        ['nome'=>'Lajeado Novo ','fk_uf'=>'10'],
        ['nome'=>'Lima Campos ','fk_uf'=>'10'],
        ['nome'=>'Loreto ','fk_uf'=>'10'],
        ['nome'=>'Luis Domingues ','fk_uf'=>'10'],
        ['nome'=>'Magalhaes de Almeida ','fk_uf'=>'10'],
        ['nome'=>'Maracacume ','fk_uf'=>'10'],
        ['nome'=>'Maraja do Sena ','fk_uf'=>'10'],
        ['nome'=>'Maranhaozinho ','fk_uf'=>'10'],
        ['nome'=>'Mata Roma ','fk_uf'=>'10'],
        ['nome'=>'Matinha ','fk_uf'=>'10'],
        ['nome'=>'Matoes do Norte ','fk_uf'=>'10'],
        ['nome'=>'Matoes ','fk_uf'=>'10'],
        ['nome'=>'Milagres do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Mirador ','fk_uf'=>'10'],
        ['nome'=>'Miranda do Norte ','fk_uf'=>'10'],
        ['nome'=>'Mirinzal ','fk_uf'=>'10'],
        ['nome'=>'Moncao ','fk_uf'=>'10'],
        ['nome'=>'Montes Altos ','fk_uf'=>'10'],
        ['nome'=>'Morros ','fk_uf'=>'10'],
        ['nome'=>'Nina Rodrigues ','fk_uf'=>'10'],
        ['nome'=>'Nova Colinas ','fk_uf'=>'10'],
        ['nome'=>'Nova Iorque ','fk_uf'=>'10'],
        ['nome'=>'Nova Olinda do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Olho dAgua das Cunhas ','fk_uf'=>'10'],
        ['nome'=>'Olinda Nova do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'PacodoLumiar ','fk_uf'=>'10'],
        ['nome'=>'Palmeirandia ','fk_uf'=>'10'],
        ['nome'=>'Paraibano ','fk_uf'=>'10'],
        ['nome'=>'Parnarama ','fk_uf'=>'10'],
        ['nome'=>'PassagemFranca ','fk_uf'=>'10'],
        ['nome'=>'PastosBons ','fk_uf'=>'10'],
        ['nome'=>'PaulinoNeves ','fk_uf'=>'10'],
        ['nome'=>'PauloRamos ','fk_uf'=>'10'],
        ['nome'=>'Pedreiras ','fk_uf'=>'10'],
        ['nome'=>'PedrodoRosario ','fk_uf'=>'10'],
        ['nome'=>'Penalva ','fk_uf'=>'10'],
        ['nome'=>'PeriMirim ','fk_uf'=>'10'],
        ['nome'=>'Peritoro ','fk_uf'=>'10'],
        ['nome'=>'Pindare Mirim ','fk_uf'=>'10'],
        ['nome'=>'Pinheiro ','fk_uf'=>'10'],
        ['nome'=>'PioXII ','fk_uf'=>'10'],
        ['nome'=>'Pirapemas ','fk_uf'=>'10'],
        ['nome'=>'Pocao de Pedras ','fk_uf'=>'10'],
        ['nome'=>'Porto Franco ','fk_uf'=>'10'],
        ['nome'=>'Porto Rico do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Presidente Dutra ','fk_uf'=>'10'],
        ['nome'=>'Presidente Juscelino ','fk_uf'=>'10'],
        ['nome'=>'Presidente Medici ','fk_uf'=>'10'],
        ['nome'=>'Presidente Sarney ','fk_uf'=>'10'],
        ['nome'=>'Presidente Vargas ','fk_uf'=>'10'],
        ['nome'=>'Primeira Cruz ','fk_uf'=>'10'],
        ['nome'=>'Raposa ','fk_uf'=>'10'],
        ['nome'=>'Riachao ','fk_uf'=>'10'],
        ['nome'=>'Ribamar Fiquene ','fk_uf'=>'10'],
        ['nome'=>'Rosario ','fk_uf'=>'10'],
        ['nome'=>'Sambaiba ','fk_uf'=>'10'],
        ['nome'=>'Santa Filomena do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Santa Helena ','fk_uf'=>'10'],
        ['nome'=>'Santa Ines ','fk_uf'=>'10'],
        ['nome'=>'Santa Luzia do Parua ','fk_uf'=>'10'],
        ['nome'=>'Santa Luzia ','fk_uf'=>'10'],
        ['nome'=>'Santa Quiteria do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Santa Rita ','fk_uf'=>'10'],
        ['nome'=>'Santana do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Santo Amaro do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Santo Antonio dos Lopes ','fk_uf'=>'10'],
        ['nome'=>'Sao Benedito do Rio Preto ','fk_uf'=>'10'],
        ['nome'=>'Sao Bento ','fk_uf'=>'10'],
        ['nome'=>'Sao Bernardo ','fk_uf'=>'10'],
        ['nome'=>'Sao DomingosdoAzeitao ','fk_uf'=>'10'],
        ['nome'=>'Sao Domingos do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Sao Felix de Balsas ','fk_uf'=>'10'],
        ['nome'=>'Sao Francisco do Brejao ','fk_uf'=>'10'],
        ['nome'=>'Sao Francisco do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Sao Joao Batista ','fk_uf'=>'10'],
        ['nome'=>'Sao Joao do Caru ','fk_uf'=>'10'],
        ['nome'=>'Sao Joao do Paraiso ','fk_uf'=>'10'],
        ['nome'=>'SaoJoaodoSoter ','fk_uf'=>'10'],
        ['nome'=>'SaoJoaodosPatos ','fk_uf'=>'10'],
        ['nome'=>'SaoJosedeRibamar ','fk_uf'=>'10'],
        ['nome'=>'SaoJosedosBasilios ','fk_uf'=>'10'],
        ['nome'=>'Sao Luis Gonzaga do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'SaoLuis ','fk_uf'=>'10'],
        ['nome'=>'Sao Mateus do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Sao Pedro da Agua Branca ','fk_uf'=>'10'],
        ['nome'=>'Sao Pedro dos Crentes ','fk_uf'=>'10'],
        ['nome'=>'Sao Raimundo das Mangabeiras ','fk_uf'=>'10'],
        ['nome'=>'Sao Raimundodo Doca Bezerra ','fk_uf'=>'10'],
        ['nome'=>'Sao Roberto ','fk_uf'=>'10'],
        ['nome'=>'Sao Vicente Ferrer ','fk_uf'=>'10'],
        ['nome'=>'Satubinha ','fk_uf'=>'10'],
        ['nome'=>'Senador Alexandre Costa ','fk_uf'=>'10'],
        ['nome'=>'Senador La Rocque ','fk_uf'=>'10'],
        ['nome'=>'Serrano do Maranhao ','fk_uf'=>'10'],
        ['nome'=>'Sitio Novo ','fk_uf'=>'10'],
        ['nome'=>'Sucupira do Norte ','fk_uf'=>'10'],
        ['nome'=>'Sucupirado Riachao ','fk_uf'=>'10'],
        ['nome'=>'Tasso Fragoso ','fk_uf'=>'10'],
        ['nome'=>'Timbiras ','fk_uf'=>'10'],
        ['nome'=>'Timon ','fk_uf'=>'10'],
        ['nome'=>'Trizidela do Vale ','fk_uf'=>'10'],
        ['nome'=>'Tufilandia ','fk_uf'=>'10'],
        ['nome'=>'Tuntum ','fk_uf'=>'10'],
        ['nome'=>'Turiacu ','fk_uf'=>'10'],
        ['nome'=>'Turilandia ','fk_uf'=>'10'],
        ['nome'=>'Tutoia ','fk_uf'=>'10'],
        ['nome'=>'Urbano Santos ','fk_uf'=>'10'],
        ['nome'=>'Vargem Grande ','fk_uf'=>'10'],
        ['nome'=>'Viana ','fk_uf'=>'10'],
        ['nome'=>'Vila Nova dos Martirios ','fk_uf'=>'10'],
        ['nome'=>'Vitoria doMearim ','fk_uf'=>'10'],
        ['nome'=>'Vitorino Freire ','fk_uf'=>'10'],
        ['nome'=>'Ze Doca ','fk_uf'=>'10'],

        ]);
    }
}
